name: ytshare
description: "Share YouTube video links with a personalized UI on your favorite social media platforms."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0
  flutter_animate: ^4.3.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  cached_network_image: ^3.3.0
  transparent_image: ^2.0.1
  photo_view: ^0.14.0
  expandable_text: ^2.3.0
  # flutter_snackbar_content: ^0.0.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  share_plus: ^11.0.0
  widgets_to_image: ^0.0.2
  lottie: ^2.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_sharing_intent: ^1.1.1
  #receive_sharing_intent: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/lottie/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ios-icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"

